[install]
# Only install package versions published at least 7 days ago
minimumReleaseAge = 604800
minimumReleaseAgeExcludes = ["@navikt/nav-dekoratoren-moduler"]

[install.scopes]
"@navikt" = { token = "$NODE_AUTH_TOKEN", url = "https://npm.pkg.github.com" }
